--- 
mygengo: 
  private_key: "EWJP}]](H-C2_7R_Oy7xr]JaSi-0|=[W#RqsO4J---o]1Qo)PBBYW6u$C=b2B(4~"
  api_key: "0M=gmtTg()]K^qC8Ux|Yzz(Td4sC)7e)|D=3u3x8#a1sfhxlZuOxmg{6AlVw#4BV"
default_locale_file: config/locales/en.yml
default_locale: en
